#ifndef VLIDATECODEONLINE_GLOBAL_H
#define VLIDATECODEONLINE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VLIDATECODEONLINE_LIB
# define VLIDATECODEONLINE_EXPORT Q_DECL_EXPORT
#else
# define VLIDATECODEONLINE_EXPORT Q_DECL_IMPORT
#endif

#endif // VLIDATECODEONLINE_GLOBAL_H
