#ifndef DAILCONNECTOR_GLOBAL_H
#define DAILCONNECTOR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DAILCONNECTOR_LIB
# define DAILCONNECTOR_EXPORT Q_DECL_EXPORT
#else
# define DAILCONNECTOR_EXPORT Q_DECL_IMPORT
#endif

#endif // DAILCONNECTOR_GLOBAL_H
